import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Timo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="og:title" content="Nhanh tay đăng kí với nhiều ưu đãi" />
        <meta name="og:image" content="https://timo.vn/wp-content/uploads/banner-desktop-3-1.jpg" />
        <meta name="description" content="Hợp tác cùng Ngân hàng Bản Việt, Timo hứa hẹn mang đến cho bạn một trải nghiệm ngân hàng cá nhân bạn vẫn luôn mong đợi, nhưng không phải phiền não với việc duy trì một số dư lớn trong tài khoản. Hãy bắt đầu lập kế hoạch cho tương lai với hàng loạt các giải pháp tiết kiệm, đầu tư và các khoản vay.
" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Learn
        </h1>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
